### ISSUE TITLE
Angular 1.3 & Angular Bootstrap 0.13

### ISSUE THREAD

**Issue by davidgoate** [compact/angular-bootstrap-lightbox#19]
Hi, I think the latest release of this plugin (0.6) specifies the bower dependencies as:

````
"angular": "^1.3.15"
"angular-bootstrap": "^0.12.1"
`````
As far as I know, Angular Bootstrap didn't support Angular 1.3 until version 0.13, which was [recently released] (https://github.com/angular-ui/bootstrap/releases/tag/0.13.0).

This leads to warnings about potential code incompatibility. E.g. 

````
angular-bootstrap#0.13.0 incompatible with ^0.12.1
````
````
Resort to using angular-bootstrap#~0.13 which resolved to angular-bootstrap#0.13.0
Code incompatibilities may occur.
````

Is there any plan to support angular-bootstrap 0.13 in the near future?

Thanks, and thanks also for the work going into this plugin!

**Comment by compact** [comment]
Updated, thanks for letting me know. As far as I'm aware, this library has no issue with angular-bootstrap#0.13.0, and can be assumed to work with future versions of angular-bootstrap unless there is a breaking change for modals.
