### ISSUE TITLE
Is it possible  video (mp4, webm)

### ISSUE THREAD

**Issue by lanceschi** [compact/angular-bootstrap-lightbox#27]
I would like to use video sources too. Like Mp4 and webm. Do you have any plan to encompass it?

Nice piece of software btw!

Cheers,
Luca

**Comment by jakeandliss** [comment]
+1

**Comment by compact** [comment]
There is support for using [ng-videosharing-embed](https://github.com/erost/ng-videosharing-embed) to embed external videos from YouTube, Vimeo, etc.

Are both of you looking to embed your own videos directly? Is there a specific Angular video library/player that you would want to use to do this?

**Comment by lanceschi** [comment]
@compact yes, I'm interested in local video files (Mp4 and WebM).

HTML <video> tag would most probably suffice although a wrapper like [MediaElement.js](http://mediaelementjs.com/) should be a more suitable candidate. I can't spot a mediaElementJs pre-cooked directive though.

Maybe a yield/delegate HTML block is to be considered in your **angular-bootstrap-lightbox** for handling local video.

Thanks

**Comment by compact** [comment]
I added a `<video>` to the default template for embedding mp4/webm/ogg files. Check the [videos demo](http://compact.github.io/angular-bootstrap-lightbox/demo5/index.html). It has controls and autoplay enabled. To customize this (maybe you want both an .mp4 and a .webm as sources for one video), you can create a custom template.

I think for MediaElement.js, a custom template makes more sense than adding it to the default template.

**Comment by lanceschi** [comment]
@compact brilliant! I just made a quick test with mp4 and webm files with the basic <video> html tag and everything works flawlessly as expected. Thanks.
