### ISSUE TITLE
isVideo error when passing image name string

### ISSUE THREAD

**Issue by irokhes** [compact/angular-bootstrap-lightbox#29]
Hi,

I'm starting to use the ligthbox, I tried to create a quick sample, passing the image url to the lightbox instead a complex object, but I'm getting and error with the function isVideo, trying to check the image.type. Does it mean that the image needs to be a complex object containing a type always?

Thanks!

P.S great work!!

**Comment by compact** [comment]
No, I think I have fixed that error.

If you mean passing into `Lightbox.openModal()`, the first argument has to be an array of strings (urls) or objects.

I made an update where you no longer have to configure the provider in order for the string urls to work. See [this demo](http://compact.github.io/angular-bootstrap-lightbox/demo4/index.html) for an example (ignore the fullScreenMode).
