### ISSUE TITLE
Only display nav if there is more than one image

### ISSUE THREAD

**Issue by Ryuno-Ki** [compact/angular-bootstrap-lightbox#34]
To use your module as replacement for jQuery prettyPhoto (which is GPL v2-licensed) I needed to make some adjustments.

To me, the lightbox nav is only required, if I load more than one image into the modal (which I don't).
So I added `data-ng-if="Lightbox.images.length > 1"` to the `.btn-group` of `.lightbox-nav`.

Maybe you want to adjust your template as well ;-)

**Comment by Wesseldr** [comment]
+1

**Comment by compact** [comment]
Fixed, sorry for the delay.
