### ISSUE TITLE
uibModal service not being injected?

### ISSUE THREAD

**Issue by jordangraft** [compact/angular-bootstrap-lightbox#42]
Having the same issue as [this user] (http://stackoverflow.com/questions/33605162/inject-provider-into-directive-not-working).  

This is the console error
```
Unknown provider: $uibModalProvider <- $uibModal <- Lightbox <- Lightbox
```

ui.boostrap is being required correctly and used on other elements in the same controller
```
var accountApp = angular.module('accountApp', [
  'ngRoute',
  'ngResource',
  'messageModule',
  'accountControllers',
  'ui.bootstrap',
  'Devise',
  'braintree-angular',
  'ngFileUpload',
  'bootstrapLightbox',
]);
```

**Comment by compact** [comment]
Which version of UI Bootstrap? I think this happens with v0.13.x and below.

**Comment by jordangraft** [comment]
Yep that was it.  I was using ui-bootstrap 0.13.4x and upgrading to 0.14.3x fixed it.

Thank you.
