### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by rem99** [compact/angular-bootstrap-lightbox#47]
Is it possible to add some multi language features to the lib? For now I have to fork repo and replace "< Previous" and "Next >"  buttons by glyphicon-chevron-left/right icons and remove "Open in new tab" button. It would be nice add some configuration for this.

**Comment by seblucas** [comment]
Not a real answer but if you override the template (as shown in the README) you can localize those strings. I did that with angular-translate and it worked perfectly.

**Comment by rem99** [comment]
Thank you. This is good solution for me.
