### ISSUE TITLE
Unknown provider: $uibModalProvider <- $uibModal <- Lightbox <- Lightbox

### ISSUE THREAD

**Issue by TommiZZ** [compact/angular-bootstrap-lightbox#49]
Hi, 
I included all the necessary files and added the 'bootstrapLightbox' as a dependency to my module, but i keep getting this error when I'm adding the 'Lightbox' parameter to my controller.
I will appreciate any help on this one.

**Comment by TommiZZ** [comment]
Problem solved. Bootstrap modal's version was out of date.

**Comment by anish-g-nair** [comment]
So what if I do not want to update my Bootstrap or Bootstrap modal?? How do I fix it?
