### ISSUE TITLE
Angular Bootstrap ^1.0 support

### ISSUE THREAD

**Issue by karensg** [compact/angular-bootstrap-lightbox#50]
Would be nice to make this library to support the new version of Angular Bootstrap.
https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes

As far as I can see, everything works. It is just the annoying dependency warning that needs to be fixed.

**Comment by seblucas** [comment]
+1

**Comment by jensbjork** [comment]
+1

**Comment by compact** [comment]
Done, sorry for the delay.
