### ISSUE TITLE
NPM install is missing index.js

### ISSUE THREAD

**Issue by Karel-TOPdesk** [compact/angular-bootstrap-lightbox#52]
When installing via NPM the index.js is missing. #41 

And something else: 
(I'm rather new with webpack so maybe this is just a mistake on my end.)
Shouldn't the index.js file require the css file? like  so:

```
require("./dist/angular-bootstrap-lightbox.css");
require('./dist/angular-bootstrap-lightbox');
module.exports = 'angular-bootstrap-lightbox';
```

Because without this the css doesn't emerge.

**Comment by tylercd100** [comment]
@compact Is it possible to bump the version from 0.10.0 to 0.10.1 to fix this issue?

**Comment by compact** [comment]
Bumped to 0.11.0, sorry for the wait.

I don't know if the stylesheet should be required, because it'd break if someone isn't using a css loader. Should that be assumed?
