### ISSUE TITLE
Plunker for this Awesome module

### ISSUE THREAD

**Issue by Sampath-Lokuge** [compact/angular-bootstrap-lightbox#58]
Hi,

I have created a Plunker for this Awesome module.If you can put that on your home page then it'll help for everyone.Thanks for the great work.Keep it up  :thumbsup:

Here it is :  [**Plunker**](http://plnkr.co/edit/pEXXDYLl0NtkqupEXaJK)

**Comment by compact** [comment]
Thanks! Added to readme.
