### ISSUE TITLE
Mobile input keyboard does not open

### ISSUE THREAD

**Issue by savcha** [compact/angular-bootstrap-lightbox#7]
Regular inputs work fine but inputs on a modal popup start to bring up the keyboard but then remove it. The only way to get keyboard to open fully is to touch input for an extended time.

Works fine on desktop, so to see the problem must use a mobile device.
http://plnkr.co/edit/cdAH7gjHToZf2KiNwBYK

Tested on iPad 8.1 and android 4.4.4 both using chrome 38.

**Comment by compact** [comment]
This appears to be the issue https://github.com/angular-ui/bootstrap/issues/2280 which has been fixed and will be included in 0.13.
