### ISSUE TITLE
templateUrl not recognized by webpack

### ISSUE THREAD

**Issue by darkdoon** [compact/angular-bootstrap-lightbox#84]
Hi,
the $uibmodal has a 'template' option besides the 'templateUrl' one. In order to manage Lightbox with webpack, I have to import my template and set it to the 'template' option. Unfortunately, I can only set the templateUrl option from the provider.

Can you add this option to lightbox please ?

Thanks for your answer.

regards,

Darkdoon.

**Comment by elementdigital** [comment]
Is this what you are looking for? this adds an option to override the uib modal window. https://github.com/compact/angular-bootstrap-lightbox/compare/master...elementdigital:master

**Comment by darkdoon** [comment]
yes, it helps :) thank you.
